style: clean redefined functions reported by pyflakes
luajit21.py:895: redefinition of unused 'noderef' from line 682
luajit21.py:1246: redefinition of unused 'tabref' from line 317
luajit21.py:1860: redefinition of unused 'irt_type' from line 1815